apiVersion: v1
kind: Pod
metadata:
  name: md-simulation-inputs-shell
spec:
  restartPolicy: Always
  containers:
    - name: shell
      image: quay.io/fedora/fedora:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: inputs
          mountPath: /mnt/inputs
  volumes:
    - name: inputs
      persistentVolumeClaim:
        claimName: md-simulation-inputs-pvc-rwx
